version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 52773:52773
    volumes:
      - ./:/irisrun/repo

  i2b2-core-server:
    build:
      context: ./dockerize_i2b2_core-server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8788:8787
      - 9991:9990
    depends_on:
      - iris

  i2b2-webclient:
    build:
      context: ./dockerize_i2b2_webclient
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8082:80
    depends_on:
      - i2b2-core-server

# DEVELOP only, targets localhost for core server
  i2b2-webclient-develop:
    build:
      context: ./dockerize_i2b2_webclient
      dockerfile: Dockerfile-develop
    restart: unless-stopped
    ports:
      - 8081:80
